services:
  mongo:
    image: mongo:7
    container_name: mongo
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - type: volume
        source: mongo_data
        target: /data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.runCommand({ ping: 1 }).ok' -u root -p root --authenticationDatabase admin | grep 1 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 60
      start_period: 20s

  backend:
    build: .
    container_name: backend
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: "3000"
      HOST: "0.0.0.0"
      DATABASE_URL: "mongodb://root:root@mongo:27017/feeds?authSource=admin&replicaSet=rs0"
      DEFAULT_FEED_URL: "https://hnrss.org/frontpage"
    ports:
      - "3000:3000"

volumes:
  mongo_data: {}