version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.runCommand({ ping: 1 })' -u root -p root --authenticationDatabase admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: backend
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: "3000"
      DATABASE_URL: "mongodb://root:root@mongo:27017/feeds?authSource=admin"
      DEFAULT_FEED_URL: "https://hnrss.org/frontpage"
    ports:
      - "3000:3000"
    #  .env:
    # env_file:
    #   - .env

volumes:
  mongo_data: